###############################################################################
#   @author         :   Trent Stanton
#   @date           :   19/12/2018
#   @package        :   Multisensors
#   @description    :   
#   @url            :   
###############################################################################
homeassistant:
  customize:
    sensor.fibaro_motion_sensor_luminance:
      device_class: illuminance
    sensor.fibaro_motion_sensor_seismic_intensity:
      icon: mdi:earth
    binary_sensor.fibaro_motion_sensor_sensor:
      device_class: motion
    binary_sensor.tampering:
      device_class: moving
      friendly_name: Living Room Tampering

group:
  multisensor:
    name: Multisensors
    entities:
      - sensor.fibaro_motion_sensor_temperature
  #    - sensor.fibaro_motion_sensor_sourcenodeid
      - sensor.fibaro_motion_sensor_luminance
      - sensor.fibaro_motion_sensor_seismic_intensity
  #    - sensor.fibaro_motion_sensor_general
  #    - sensor.fibaro_motion_sensor_burglar
      - binary_sensor.fibaro_motion_sensor_sensor
      - binary_sensor.tampering
      - binary_sensor.motion_hallway
      - sensor.temperature_bedroom
      - sensor.humidity_bedroom
  motionsensors:
      - binary_sensor.fibaro_motion_sensor_sensor
      - binary_sensor.motion_hallway
      - binary_sensor.motion_bedroom
  

binary_sensor:
  - platform: template
    sensors:
      tampering:
        entity_id:
          - sensor.fibaro_motion_sensor_burglar
        value_template: '{{ is_state("sensor.fibaro_motion_sensor_burglar", "3") }}'
input_boolean:
  disable_unexpected_motion_notification:
    name: Disable Unexpected Motion Notification
    initial: off
    icon: mdi:shield-outline
  disable_device_tampering_notification:
    name: Disable Device Tampering Notification
    initial: off
    icon: mdi:shield-outline
  disable_current_temperature_notification:
    name: Disable Current Temperature Notification
    initial: off
    icon: mdi:thermometer

###############################################################################
#                               Automations
###############################################################################
automation:
  - alias: Unexpected Motion Notification
    trigger:
    - platform: state
      entity_id: binary_sensor.fibaro_motion_sensor_sensor
      to: 'on'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.disable_unexpected_motion_notification
        state: 'off'
      - condition: state
        entity_id: device_tracker.rachels_iphone
        state: 'not_home'
      - condition: or
        conditions:
        - condition: state
          entity_id: device_tracker.trent_trent
          state: 'not_home'
        - condition: state
          entity_id: device_tracker.trent_trent
          state: '!secret work_state'
    action:
    - service: notify.trent
      data_template:
        message: "Unexpected Motion in Living Room Detected!"
  - alias: Device Tampering Notification
    trigger:
    - platform: state
      entity_id: binary_sensor.tampering
      to: 'on'
    condition:
    - condition: state
      entity_id: input_boolean.disable_device_tampering_notification
      state: 'off'
    action:
    - service: notify.trent
      data_template:
        message: "Tampering of Living Room Sensor Detected!"
  - alias: Current Temperature Notification
    trigger:
    - platform: time
      at: '17:00'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.disable_current_temperature_notification
        state: 'off'
      - condition: numeric_state
        entity_id: 'sensor.fibaro_motion_sensor_temperature'
        above: '23'
      - condition: state
        entity_id: device_tracker.rachels_iphone
        state: 'not_home'
      - condition: or
        conditions:
        - condition: state
          entity_id: device_tracker.trent_trent
          state: 'not_home'
        - condition: state
          entity_id: device_tracker.trent_trent
          state: '!secret work_state'
    action:
    - service: notify.trent
      data_template:
        title: "Home Temperature"
        message: "Home is currently at {{ states.sensor.fibaro_motion_sensor_temperature.state }} °C."
        data:
          actions:
          - action: open
            title: Open Home Assistant
            url: !secret base_url
          - action: startac
            title: Start AC
  - alias: startac push notification action button clicked
    trigger:
    - platform: event
      event_type: html5_notification.clicked
      event_data:
        action: startac
    action:
    - service: script.turn_on
      entity_id: script.start_air_conditioner