###############################################################################
#   @author         :   Trent Stanton
#   @date           :   22/12/2018
#   @package        :   Welcome Home
#   @description    :   
#   @url            :   Base Setup from: https://mikefez.com/home-assistant-tracking-recent-arrivals-having-alexa-welcome-them/
###############################################################################
input_boolean:
  disable_welcome_home:
    name: Disable Welcome Home Message
  welcome_home_weather_component:
    name: Welcome Home Weather Component

input_number:
  consider_recent_arrival_mins:
    name: Consider Recent Arrival Max Mins
    min: 1
    max: 10
    step: 1

binary_sensor:
  - platform: template
    sensors:
      recent_arrival_trent:
        friendly_name: "Recent Arrival: Trent"
        value_template: >-
          {{ states('sensor.time') and is_state("device_tracker.google_maps_109209758211303121867", "home") and as_timestamp(now()) - as_timestamp(states.device_tracker.google_maps_109209758211303121867.last_changed | default(0)) | int <= 60 * (states.input_number.consider_recent_arrival_mins.state | int) }}
      recent_arrival_rachel:
        friendly_name: "Recent Arrival: Rachel"
        value_template: >-
          {{ states('sensor.time') and is_state("device_tracker.rachels_iphone", "home") and as_timestamp(now()) - as_timestamp(states.device_tracker.rachels_iphone.last_changed | default(0)) | int <= 60 * (states.input_number.consider_recent_arrival_mins.state | int) }}

###############################################################################
#                               Automations
###############################################################################
automation:
  - alias: "Welcome Home Announcement"
    trigger:
      - platform: state
        entity_id: binary_sensor.door_frontdoor  # Front Door Sensor
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.disable_welcome_home
          state: 'off'
        - condition: or
          conditions:
            - condition: state
              entity_id: binary_sensor.recent_arrival_trent
              state: 'on'
            - condition: state
              entity_id: binary_sensor.recent_arrival_rachel
              state: 'on'
    action:
      - delay: 00:00:03  # Lengthen the delay if Google Assistant is speaking before fully through the door
      - service: script.speech_processing
        data_template:
          speech_message: >
            {% if now().strftime("%H")|int < 12 %}
              Good morning,
            {% elif now().strftime("%H")|int < 18 %}
              Good afternoon,
            {% else %}
              Good evening,
            {% endif %}
            {% if is_state("binary_sensor.recent_arrival_trent", "on") and is_state("binary_sensor.recent_arrival_rachel", "on")  %}
              Stanton Family
            {% elif is_state("binary_sensor.recent_arrival_trent", "on") %}
              Trent
            {% elif is_state("binary_sensor.recent_arrival_rachel", "on") %}
              Rachel
            {% endif %}
            .
            {% if is_state("input_boolean.welcome_home_weather_component", "on") %}
              It's currently {{states.sensor.weather_temperature.state|round}} degrees outside and {{states.sensor.fibaro_motion_sensor_temperature.state|round}} degrees inside.
            {% endif %}
            {% if is_state("input_boolean.welcome_home_weather_component", "on") and states.sensor.fibaro_motion_sensor_temperature.state > '22' and states.sensor.weather_temperature.state > states.sensor.fibaro_motion_sensor_temperature.state  %}
              The Air Conditioner Should be started to cool down the home.
            {% elif is_state("input_boolean.welcome_home_weather_component", "on") and states.sensor.fibaro_motion_sensor_temperature.state > '22' and states.sensor.fibaro_motion_sensor_temperature.state > states.sensor.weather_temperature.state  %}
              The windows should be opened to cool down the home.
            {% elif is_state("input_boolean.welcome_home_weather_component", "on") and states.sensor.fibaro_motion_sensor_temperature.state < '15' and states.sensor.weather_temperature.state < states.sensor.fibaro_motion_sensor_temperature.state  %}
              The Heater Should be turned on to warm up the home.
            {% elif is_state("input_boolean.welcome_home_weather_component", "on") and states.sensor.fibaro_motion_sensor_temperature.state < '15' and states.sensor.fibaro_motion_sensor_temperature.state < states.sensor.weather_temperature.state  %}
              The windows should be opened to warm up the home.
            {% endif %}