###############################################################################
#   @author         :   Trent Stanton
#   @date           :   16/12/2018
#   @package        :   Xiaomi Buttons
#   @description    :   Xiaomi Buttons via MQTT
#   @url            :   
###############################################################################

script:
## Trent Bed Room Button - Turn Trent Bedside Lamp on
  trent_bed_room_button_single:
    sequence:
      - service: light.toggle
        data:
          entity_id: light.trent_bedside
## Trent Bed Room Button - Turn Both Bedside Lamps on
  trent_bed_room_button_double:
    sequence:
      - service: scene.turn_on
        data:
          entity_id: scene.bedroom_default
  trent_bed_room_button_triple:
    sequence:
      - service: scene.turn_on
        data:
          entity_id: scene.bedroom_romantic
#  trent_bed_room_button_quadruple:
#  trent_bed_room_button_many:
## Trent Bed Room Button - Good Night
  trent_bed_room_button_long:
    sequence:
      - service: script.turn_on
        data:
          entity_id: script.good_night
#  trent_bed_room_button_long_release:
## Rachel Bed Room Button - Turn Rachel Bedside Lamp on
  rachel_bed_room_button_single:
    sequence:
      - service: light.toggle
        data:
          entity_id: light.rachel_bedside
## Rachel Bed Room Button - Turn Both Bedside Lamps on
  rachel_bed_room_button_double:
    sequence:
      - service: scene.turn_on
        data:
          entity_id: scene.bedroom_default
  rachel_bed_room_button_triple:
    sequence:
      - service: scene.turn_on
        data:
          entity_id: scene.bedroom_romantic
#  rachel_bed_room_button_quadruple:
#  rachel_bed_room_button_many:
## Rachel Bed Room Button - Good Night
  rachel_bed_room_button_long:
    sequence:
      - service: script.turn_on
        data:
          entity_id: script.good_night
#  rachel_bed_room_button_long_release:
## Entryway Wall Switch - Entryway Light
  wall_switch_entryway_left:
    sequence:
      - service: light.toggle
        data:
          entity_id: light.entryway
## Entryway Wall Switch - Entry Light
  wall_switch_entryway_right:
    sequence:
      - service: light.toggle
        data:
          entity_id: light.entry

###############################################################################
#                               Automations
###############################################################################
automation:

############################################################
#
# Trent Bed Room Button
#
############################################################

  - alias: Trent Bed Room Button
    trigger:
      platform: mqtt
      topic: 'zigbee2mqtt/0x00158d000186e632'
    condition:
      condition: template
      value_template: "{{ trigger.payload_json.click in ('single','double','triple','quadruple','many','long') }}"
    action:
      - service_template: >
          {% if trigger.payload_json.click == 'single' %}
            script.trent_bed_room_button_single
          {% elif trigger.payload_json.click == 'double' %}
            script.trent_bed_room_button_double
          {% elif trigger.payload_json.click == 'triple' %}
            script.trent_bed_room_button_triple
          {% elif trigger.payload_json.click == 'quadruple' %}
            script.trent_bed_room_button_quadruple
          {% elif trigger.payload_json.click == 'many' %}
            script.trent_bed_room_button_many
          {% elif trigger.payload_json.click == 'long' %}
            script.trent_bed_room_button_long
          {% elif trigger.payload_json.click == 'long_release' %}
            script.trent_bed_room_button_long_release
          {% else %}
          {% endif %}

############################################################
#
# Rachel Bed Room Button
#
############################################################

  - alias: Rachel Bed Room Button
    trigger:
      platform: mqtt
      topic: 'zigbee2mqtt/0x00158d00016449a2'
    condition:
      condition: template
      value_template: "{{ trigger.payload_json.click in ('single','double','triple','quadruple','many','long') }}"
    action:
      - service_template: >
          {% if trigger.payload_json.click == 'single' %}
            script.rachel_bed_room_button_single
          {% elif trigger.payload_json.click == 'double' %}
            script.rachel_bed_room_button_double
          {% elif trigger.payload_json.click == 'triple' %}
            script.rachel_bed_room_button_triple
          {% elif trigger.payload_json.click == 'quadruple' %}
            script.rachel_bed_room_button_quadruple
          {% elif trigger.payload_json.click == 'many' %}
            script.rachel_bed_room_button_many
          {% elif trigger.payload_json.click == 'long' %}
            script.rachel_bed_room_button_long
          {% elif trigger.payload_json.click == 'long_release' %}
            script.rachel_bed_room_button_long_release
          {% else %}
          {% endif %}

############################################################
#
# Entryway Button
#
############################################################

  - alias: Trent Entryway Button
    trigger:
      platform: mqtt
      topic: 'zigbee2mqtt/0x00158d000170ef78'
    condition:
      condition: template
      value_template: "{{ ('left','right') in trigger.payload_json.click }}"
    action:
      - service_template: >
          {% if trigger.payload_json.click == 'left' %}
            script.wall_switch_entryway_left
          {% elif trigger.payload_json.click == 'right' %}
            script.wall_switch_entryway_right
          {% else %}
          {% endif %}